/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.38.0
  Forc version: 0.35.5
  Fuel-Core version: 0.17.3
*/

export type { StrExperimentAbi } from './StrExperimentAbi';

export { StrExperimentAbi__factory } from './factories/StrExperimentAbi__factory';
