/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.73.0
  Forc version: 0.49.2
  Fuel-Core version: 0.22.0
*/

export type { TestContractAbi } from './TestContractAbi';

export { TestContractAbi__factory } from './factories/TestContractAbi__factory';
