/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.73.0
  Forc version: 0.49.2
  Fuel-Core version: 0.22.0
*/

import type {
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

export type AddressInput = { value: string };
export type AddressOutput = AddressInput;

interface TestContractAbiInterface extends Interface {
  functions: {
    register: FunctionFragment;
    resolve: FunctionFragment;
  };

  encodeFunctionData(functionFragment: 'register', values: [string, AddressInput, string]): Uint8Array;
  encodeFunctionData(functionFragment: 'resolve', values: [string]): Uint8Array;

  decodeFunctionData(functionFragment: 'register', data: BytesLike): DecodedValue;
  decodeFunctionData(functionFragment: 'resolve', data: BytesLike): DecodedValue;
}

export class TestContractAbi extends Contract {
  interface: TestContractAbiInterface;
  functions: {
    register: InvokeFunction<[name: string, owner: AddressInput, ethereum: string], void>;
    resolve: InvokeFunction<[name: string], [AddressOutput, string]>;
  };
}
